// Run with NODE_PATH pointing to a Playwright installation. Uses only isolated test data.
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const appUrl = process.env.APP_URL || 'http://127.0.0.1:18080/';
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const output = path.resolve('artifacts'); fs.mkdirSync(output, { recursive: true });
  await page.goto(appUrl);
  await page.getByRole('heading', {name:'登录工作空间'}).waitFor();
  await page.screenshot({ path: path.join(output,'login-desktop.png'), fullPage:true });
  await page.getByLabel('账号', {exact:true}).fill('admin');
  await page.getByLabel('密码', {exact:true}).fill('Local-preview-only-928!');
  await page.getByRole('button', {name:'进入工作空间'}).click();
  await page.waitForURL('**/#/');
  await page.locator('.app-nav a').first().click();
  await page.locator('.dialog-input').fill('试运行验证项目');
  await page.locator('.dialog-actions .btn-ok').click();
  await page.waitForURL('**/#/chat/**');
  const projectId = page.url().split('/').pop();
  await page.locator('.context-textarea').fill('D1 团队负责人：张工；职责：协调问题分析。');
  // Switch before the debounce fires: D1 notes must never land in D2.
  await page.locator('.step-item').filter({hasText:'D2'}).click();
  await page.waitForTimeout(1100);
  const context = await page.evaluate(async id => (await fetch(`/api/projects/${id}/contexts/latest`)).json(), projectId);
  if (!context.step_states.D1.context_notes.includes('张工') || context.step_states.D2.context_notes.includes('张工')) throw Error('Cross-step autosave regression');
  await page.locator('.context-textarea').fill('D2：表面划伤，需要补充发生时间和批次。');
  await page.waitForTimeout(1100);
  await page.getByRole('button',{name:'手动填写',exact:true}).click();
  await page.getByPlaceholder('输入本阶段报告内容，确认后保存').fill('已确认：待核实表面划伤发生批次及数量。');
  await page.locator('.output-actions .btn-confirm').click();
  await page.getByPlaceholder('输入本阶段报告内容，确认后保存').waitFor({state:'hidden'});
  await page.reload();
  await page.locator('.context-textarea').waitFor();
  if (!(await page.locator('.context-textarea').inputValue()).includes('表面划伤')) throw Error('Reload lost saved notes');
  await page.screenshot({path:path.join(output,'workspace-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(500);
  await page.screenshot({path:path.join(output,'workspace-mobile.png'),fullPage:true});
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 2);
  if (overflow) throw Error('Mobile horizontal overflow');
  const sidebar = await page.locator('.sidebar').boundingBox();
  if (sidebar && sidebar.x + sidebar.width > 2) throw Error('Mobile sidebar did not close');
  await page.getByRole('link',{name:'账号',exact:true}).click();
  await page.getByRole('heading',{name:'账号与数据'}).waitFor();
  await page.screenshot({path:path.join(output,'account-mobile.png'),fullPage:true});
  await page.getByText('退出',{exact:true}).click();
  await page.getByRole('heading',{name:'登录工作空间'}).waitFor();
  await page.screenshot({path:path.join(output,'login-mobile.png'),fullPage:true});
  await browser.close();
  if (errors.length) throw Error(errors.join('\n'));
  console.log('PASS: login, project creation, cross-step autosave, mobile overflow, account, logout.');
})().catch(error => { console.error(error); process.exit(1); });
